version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y zip unzip

  build:
    commands:
      - echo "Zipping application..."
      - zip -r app.zip . -x "*.git*" "tests/*" "scripts/*"

  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - app.zip
